feature: 주문취소 기능 구현
LOTTE-5IVE/kka-kka pull request #113
Opened 2022-10-19 10:11 UTC by tlsdnwn55

## Resolve #109 

### 설명
- 주문취소 기능을 구현하였습니다. ( 24시간 전 주문만 가능 ) 
- mysql은 자기 참조 테이블을 update or delete 하지 못하는 문제를 발견하여 기존 장바구니 삭제 로직을 변경하였습니다.
- 취소 여부를 확인하기 위해 product_order 엔티티에  Integer deleted 컬럼을 추가하였습니다. ( default = 0 , 삭제 = 1 )
- 주문 정보를 불러올때 deleted 를 활용하여 프론트에서 취소 여부에 따라 처리할 수 있습니다.

![image](https://user-images.githubusercontent.com/48666403/196663178-e7974cb8-cef4-4f89-a7ad-a3b42101dc75.png)

2022-10-19 11:07 UTC, soulgchoi requested changes
기능 구현하느라 고생하셨습니다👍
제가 남긴 코멘트들은 사실 반영 할 필요는 없는데.... 
flyway 관련해서는 저게 정해져있는거라 꼭 고쳐야해서 리퀘스트 체인지 남길게요😭😭😭

2022-10-19 11:07 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/order/application/OrderService.java
> +            }
이 부분 `Order` 도메인 내부 로직으로 처리하는 쪽이 더 객체지향적일 것 같아요!
```java
// Order
public boolean isOrderedAtInDay() {
    return this.orderedAt.plusHours(24).isBefore(LocalDateTime.now()));
}
```
이렇게 이 주문이 24시간 이내에 주문한 것인지 아닌지 객체에 직접 물어보는거죠!!
그런데 `productOrder.getOrder().isOrderedAtInDay()` 가 되는것보단...
```java
// ProductOrder
public boolean isOrderedAtInDay() {
    return this.order.isOrderedAtInDay();
}
```
요런식으로 `ProductOrder` 에서 직접 판단하는 것처럼 만들면 더 좋을거 같슴다

2022-10-19 11:07 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/member/member/ui/dto/ProductOrderResponse.java
> +        return new ProductOrderResponse(id, price, quantity, deleted,productResponse, reviewResponse);
```suggestion
            Integer quantity, Integer deleted, ProductResponse productResponse, ReviewSimpleRespnse reviewResponse) {
        return new ProductOrderResponse(id, price, quantity, deleted, productResponse, reviewResponse);
```

2022-10-19 11:07 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/order/application/dto/MemberProductOrderDto.java
> +                    productOrder.getDeleted(),
이렇게 실제로 값이 추가된걸 보니 관리지점을 통일한 보람이 있네요..🥹👍

2022-10-19 11:07 UTC, soulgchoi commented on backend/main-service/src/main/resources/db/migration/V2210191457_add_productorder_deleted.sql
> +ALTER TABLE product_order ADD COLUMN deleted INTEGER(1);
flyway 네이밍은 꼭 `V{버전}__{설명}.sql` 이렇게 해야해서... add 앞에 언더바 두개로 바꿔주세요!!

2022-10-20 02:36 UTC, soulgchoi approved these changes
점점 속도가 빨라지는게 보이네요👍👍

2022-10-20 06:17 UTC, devpoooh approved these changes
짱입니다!!

2022-10-20 06:21 UTC, merged