feat: 카테고리 상품 목록 조회 , 상세 보기 기능 구현
LOTTE-5IVE/kka-kka pull request #17
Opened 2022-09-23 05:14 UTC by tlsdnwn55

## Resolve #6 

### 설명
- 카테고리별 페이징 상품 목록 조회 기능 과 상품 상세보기 API를 구현하였습니다.
- @PostConsructor 를 통해 더미 데이터를 넣어뒀습니다. ( 추후 삭제 요망 )
![image](https://user-images.githubusercontent.com/48666403/191895645-36889d03-69bc-428d-86f4-5ab2d3a71952.png)

- API uri
- category/{categoty_id}?page={number} ex) category/1?page=0
- product/{product_id}

- FE 개발자와 1페이지에 나타낼 Size 조정이 필요합니다.
![image](https://user-images.githubusercontent.com/48666403/191895792-79fae146-c205-4fe9-8296-513cc3ee18ab.png)
![image](https://user-images.githubusercontent.com/48666403/191895814-1bf6e28f-8e0e-493b-b67c-e9089e5a0729.png)

### 기타
- 정렬 기준등 상세 처리 필요

2022-09-23 05:33 UTC, zihuns approved these changes

2022-09-23 05:46 UTC, omj9803 approved these changes

2022-09-23 06:06 UTC, soulgchoi requested changes
코멘트 쩜 많이 남겼는데 DI 부분은 꼭 반영 부탁합니당~!
다른 부분은 생각해보고 별로면 그냥 본인 소신대로 작성하면 좋겠습니다! (대신 피드백 plz 왜 그렇게 했는지 궁금함)

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +    }
```suggestion
@Service
public class CartService {

    private final CartRepository cartRepository;
    private final CartItemRepository cartItemRepository;
    private final ProductRepository productRepository;

    public CartService(CartRepository cartRepository, CartItemRepository cartItemRepository, ProductRepository productRepository) {
        this.cartRepository = cartRepository;
        this.cartItemRepository = cartItemRepository;
        this.productRepository = productRepository;
    }
```

`@Autowired` 는 빼도 될거예요
이왕 생성자 주입 방식으로 DI를 해주고 있으니 `private final`로 선언해 생성자 주입 방식의 이점을 누려봅시당!

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/domain/Cart.java
> +    List<CartItem> cartItems = new ArrayList<>();
```suggestion
    private List<CartItem> cartItems = new ArrayList<>();
```

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/domain/Cart.java
> +    private Long Id;
필드명은 카멜케이스로..! 
```suggestion
    private Long id;
```

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/domain/Cart.java
> +    private Long Id;
필드명은 카멜케이스로..! 
```suggestion
    private Long id;
```

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/domain/Cart.java
> +    @Column(name = "CART_ID")
그냥 id 여도 되지 않을까요?

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/domain/CartItem.java
> +    private Product product;
```suggestion
    @OneToOne
    @JoinColumn(name = "product_id")
    private Product product;
```

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/domain/CartItem.java
> +    private Integer price;
이거 논의 한번 해보고 싶네요. 카트 아이템에 price가 필요할까요? 상품으로 가격을 계산할 수 있는데..🤔

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/domain/CartItem.java
> +    }
모든 필드값을 포함하는 생성자를 만들려는 의도였다면 `price`가 있어야할거고,
`cart`, `product`, `quantity` 만 포함하는 생성자를 의도한거라면 전체 필드 생성자를 추가한 뒤 부생성자로 만드는게 좋을 것 같아요.

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/domain/repository/CartRepository.java
> +//    Cart findByMemberId(Long id);
카트를 아직 구현 안해서 구현 예정인 기능을 넣어둔 거라고 생각되지만.. 그냥 지워도 되지 않을까요?😂

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
> +    }
여기도 `private final`로 선언하고 `@Autowired` 빼면 좋을 것 같습니다!

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
> +        cartService.saveCartItem(cartItem);
`cartItem` 이라는 이름은 우리 엔티티 `CartItem`의 인스턴스처럼 생각되어요. 그냥 `cartRequest` 나 `cartRequestDto`면 되지 않을까욥

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/category/application/CategoryService.java
> +    }
여기도 DI 부분 수정!!

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/category/domain/Category.java
> +    @Column(name = "CATEGORY_ID")
```suggestion
```
엔티티 PK를 그냥 id 로 쓰는건 일단 제가 선호하는 방식입니다! 뭐가 더 좋은지는 잘 모르겠음!

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/category/ui/CategoryController.java
> +    }
🥺

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/category/ui/CategoryController.java
> +    }
이건 테스트용 메서드인가요..? 👀

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/category/ui/CategoryController.java
> +        System.out.println("hasNext: " + result.hasNext());
테스트용 콘솔 출력문은 지워주세요~
우리 로그로 남겨야할 값이라면 로거 선언해서 적절한 레벨로 남겨주시면 좋을 것 같습니다!

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/category/ui/dto/ResponseCategoryProducts.java
> +    private Date registered_at;
```suggestion
    private String imageUrl;
    private Integer discount;
    private Date registeredAt;
```

자바에서는 카멜케이스로 쓰는게 어떨까요!

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/product/application/ProductService.java
> +    }
👀

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/product/application/ProductService.java
> +        ProductResponseDto result = mapper.map(productDetail.get(), ProductResponseDto.class);
`productDetail.get()` 부분에 예외처리가 있으면 좋겠어요. NPE가 생길 수도 있겠네요~

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/product/application/ProductService.java
> +        ModelMapper mapper = new ModelMapper();
ModelMapper 는 매번 새로 생성하는 것보다 빈으로 등록하고 주입해서 쓰면 더 좋을 것 같습니다!

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/product/application/ProductService.java
> +        result.setCategoryName(productDetail.get().getCategory().getName());
디미터법칙....

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/product/domain/Product.java
> +    private String nutrition_info_url;
```suggestion
    @Column(nullable = true, name = "image_url")
    private String imageUrl;
    @Column(name = "detail_image_url")
    private String detail_imageUrl;
    @Column(name = "nutritionInfoUrl")
    private String nutritionInfoUrl;
```

프로덕션 코드에는 카멜케이스로 쓰고 DB 컬럼 네임을 지정해주면 더 좋을 것 같습니다!

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/product/domain/Product.java
> +    }
```suggestion
    public Product(Long id, Category category, String name, int price, int stock, String imageUrl, String detailImageUrl, String nutritionImageUrl) {
        this.id = id;
        this.category = category;
        this.name = name;
        this.price = price;
        this.stock = stock;
        this.imageUrl = imageUrl;
        this.detailImageUrl = detailImageUrl;
        this.nutritionInfoUrl = nutritionInfoUrl;
    }
    
    public Product(Category category, String name, int price, int stock, String image_url, String detail_image_url) {
        this(null, category, name, price, stock, imageUrl, detailImageUrl, null);
    }
```

이렇게 부생성자로 만들어보아요.
엘레강트 오브젝트 보면 부생성자를 많이 만들라는 얘기가 나오는걸로 기억하는디 저도 이 의견에 동의해요.

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/product/ui/ProductController.java
>  @RequestMapping("/product")
`product` 보다 `products` 가 더 낫지 않을까요

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/product/ui/ProductController.java
> +    }
👀

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/product/ui/ProductController.java
> +    }
이건모죠

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/product/ui/ProductController.java
> +    public ResponseEntity<ProductResponseDto> getProductDetail(@PathVariable("productId") Long productId) {
좀 더 컨트롤러 레이어에서 동작하는.. 이름을 생각하자면.. `showProductDetail` 이런 메서드명도 좋을 것 같아요.
get 은 코드단인데 여기서는 UI로서 행위를 표현하는 느낌으로?

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/product/ui/dto/ProductResponseDto.java
> +    private Long id;
여기 개행 통일해주세요~!
저는 클래스 명 아래에는 보통 이렇게 한줄 띄는 편인데 다른 클래스들은 안그런게 더 많네요 하나로 맞춰주삼😉

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/product/ui/dto/ProductResponseDto.java
> +    private String nutrition_info_url;
여기도 카멜케이스로 작성부탁합니다~
프론트에 스네이크 케이스로 json response 전달하고 싶으면 `@JsonProperty(value = "image_url")` 이렇게 쓰면 됩니당

2022-09-23 06:06 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +    }
이 메서드 뭔가 쓰는건가요?

2022-09-23 06:09 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +    }
작성중입니다 ㅜㅜ

2022-09-23 06:09 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/product/ui/dto/ProductResponseDto.java
> +    private String nutrition_info_url;
수정하겟습니다 ㅜㅜ

2022-09-23 06:09 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/product/ui/dto/ProductResponseDto.java
> +    private Long id;
한줄통일하겟슴다 ㅜㅜ

2022-09-23 06:10 UTC, soulgchoi commented
그리고 **페이지 1로 표시하도록** 바꿀 수 있어요. 보통 프론트에서는 1이라고 생각할테니 0이라고 상호간에 합의가 되지 않았으면 보편적인 기준으로 만들어주면 좋을거 같다는 의견입니닷!

2022-09-23 06:10 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/product/ui/ProductController.java
> +    }
apigate-way에서 컨트롤러 별로 라우팅해주는지 궁금해서 테스트한다고 써놨습니다 ㅜ

2022-09-23 06:11 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +    }
생성자주입 방식의 이점을 누려보겠습니다 !

2022-09-23 06:16 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/domain/Cart.java
> +    List<CartItem> cartItems = new ArrayList<>();
코드리뷰 감사합니다

2022-09-23 06:16 UTC, soulgchoi requested changes

2022-09-23 06:16 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/dto/CartRequestDto.java
> +@Data
`@Data` 어노테이션은 setter 를 포함하는걸로 아는데, setter 가 필요하지 않으니 사용을 지양하는 편이 좋다는게 제 의견입니다!

2022-09-23 06:19 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/product/domain/Product.java
> +    private String nutrition_info_url;
```suggestion
    @Column(nullable = true, name = "image_url")
    private String imageUrl;
    @Column(name = "detail_image_url")
    private String detailImageUrl;
    @Column(name = "nutrition_info_url")
    private String nutritionInfoUrl;
```

ㅎㅎㅎ 고치다가 좀 빼먹었는데 찰떡같은 이해 부탁드립니다....

2022-09-23 06:19 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/product/ui/ProductController.java
> +    public ResponseEntity<ProductResponseDto> getProductDetail(@PathVariable("productId") Long productId) {
바로 반영했습니다 네이밍 감사합니다

2022-09-23 06:21 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/dto/CartRequestDto.java
> +@Data
Dto에 setter 지양하겠습니다 ㅜㅜ

2022-09-23 07:26 UTC, soulgchoi approved these changes
고생하셨습니다👍
앞으로 다른 기능 구현하면서도 또 이것저것 맞추고 시도해보아요

2022-09-23 07:26 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/member/ui/MemberController.java
> +    }
나중에 고칠거라고 생각되지만 Controller 에서 Repository를 의존하는건...!
그리고 테스트로 급하게 써서 그런지 여기만 Autowired네용

2022-09-23 07:29 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/category/domain/repository/CategoryRepository.java
> +}
갑자기 든 생각인데 카테고리 기준으로 product 를 가져온다면 사실 주체는 product 인데 그럼 이건 product의 일이 아닌가.. 하는 생각이 드네요...

2022-09-23 07:29 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/category/ui/CategoryController.java
> +    @GetMapping("/{categoryId}")
위에 또 남긴 코멘트처럼 `/products?category={catetoryId}` 로 만든다면 전체 목록 조회와 카테고리로 조회하는 api 가 좀 더 잘 표현되지 않을까? 하는 생각이

2022-09-23 07:31 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/member/ui/MemberController.java
> +    }
급하게 테스트용으로 해서 그렇습니다 !

2022-09-23 07:32 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/category/domain/repository/CategoryRepository.java
> +}
저도 이게 햇갈렸는데 롯데는 products 기준인듯하고 신세계는 catogory 기준으로 가져오는거 같습니다 ...

2022-09-23 07:34 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/category/ui/CategoryController.java
> +    @GetMapping("/{categoryId}")
@GetMapping(/products?category={categoryId}) 로 고칠게요 ~! 저도 API URI 가 너무 별로인거 같아 고민중이였습니다 감사합니다

2022-09-23 07:48 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/domain/CartItem.java
> +    private Product product;
@ManyToOne(fetch = FetchType.LAZY)
    private Cart cart;
    @ManyToOne(fetch = FetchType.LAZY)
    private Product product;
여기는 이렇게 수정했습니다

2022-09-23 07:49 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/domain/CartItem.java
> +    private Integer price;
저도 구현하면서 같은 생각했습니다 ! 그래서 CartRequestDto 에 price 안넣고 productId만 넣었습니다

2022-09-23 08:34 UTC, soulgchoi reviewed
반영하기 쉬운 간단한 코멘트만 좀 더 남겼습니다~
예외처리는 나중에 컨벤션 정해서 추가하면 될 것 같고, 디미터 법칙에 관련해서 코멘트 남긴게 있는데 그건 의견공유 바랍니닷👍

2022-09-23 08:34 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/domain/Cart.java
> +    }
이거 둘 중 하나만 있으면 될거같아요ㅎㅎ

2022-09-23 08:34 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/domain/Cart.java
>      }
이거 둘 중 하나만 있어도 될거같아요ㅎㅎ

2022-09-23 08:34 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/category/application/CategoryService.java
>                          p.getRegistered_at()
혼자 스네이크랑 카멜이랑 섞여있네요!

2022-09-23 08:34 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/category/ui/CategoryController.java
> +    @GetMapping("/{categoryId}")
그렇다면 CategoryController가 아니라 ProductController로 가겠네요 굿👍

2022-09-23 08:34 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/common/config/WebConfig.java
> +        };
p 는 뭐죵

2022-09-23 08:37 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/common/config/WebConfig.java
> +        };
복붙해와서 저도 잘 모르겟어요 ㅜㅜ

2022-09-26 01:24 UTC, soulgchoi approved these changes
기능 구현에 더해 피드백 반영까지 고생많으셨습니다!
- 예외처리가 하나도 안되어있는데 차차 고민해보시면 좋을 것 같아요
- 롬복으로 생성자 만들 때 여기저기 통일성이 없는데 저의 경우 기준을 만들어서 사용하면 작업 효율이 더 좋아지더라구요! (Product와 Category 같은 경우..)
- 일일이 DB를 확인하거나 직접 API 요청을 보내 확인해야 하다보니, 테스트 코드 작성을 고려해보셨으면..!
- GET `/products`는 카테고리 아이디 분기만 나누면 상품 목록 조회로 뚝딱 완성될 것 같습니다! 좋네용!

그리고.. 이 코드는 클라이언트 페이지에서 접근하면 CORS 에러가 터질겁니다😉

2022-09-26 01:24 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/product/ui/ProductController.java
> +
```suggestion
    // Logger 선언
    // Logger log = LoggerFactory.getLogger(ProductController.class);

        log.info("전체 페이지 수: {}", result.getTotalPages());
        log.info("전체 상품목록 수: {}", result.getTotalElements());
        log.info("현제 페이지(기본0): ", result.getNumber());
        log.info("hasNext: {}", result.hasNext());
```

로그로 꼭 남겨야 하는 정보는 저라면 이렇게 남길 것 같네요ㅎㅎ

2022-09-26 01:26 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/common/config/WebConfig.java
> +        };
`PageableHandlerMethodArgumentResolverCustomizer`에 커스텀해서 반환하는거네요 이해 완.

2022-09-26 01:28 UTC, devpoooh approved these changes
참고 많이 하겠습니다.
고생하셨어요~

2022-09-26 01:35 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/product/ui/ProductController.java
> +
산넘어산으로 해결할게 산더미네요 ㅜ 피드백 감사합니다

2022-09-26 01:37 UTC, merged