feat: 회원/비회원 상품에 대한 쿠폰 조회 API 추가
LOTTE-5IVE/kka-kka pull request #183
Opened 2022-11-02 10:51 UTC by omj9803

## Resolve #181 #176

### 설명
- 상세 페이지에서의 상품 쿠폰 조회
    - 회원 : 가지고 있는 등급 쿠폰 + 상품에 대한 쿠폰 모두 확인 가능, 최대 할인가 확인 가능
    - 비회원 : 상품에 대한 쿠폰만 확인 가능
    
- 장바구니/결제 페이지에서의 상품 쿠폰 조회
    - 보유중인 쿠폰 + 다운로드 가능한 쿠폰 모두 조회 가능
    
- 쿠폰 API 문서 추가

![image](https://user-images.githubusercontent.com/34434135/199471220-1f3b39fa-5dc0-411a-b1e7-2518dc110269.png)
![image](https://user-images.githubusercontent.com/34434135/199471347-056981b7-def8-478c-889b-7c58d1b3f3ce.png)

2022-11-02 11:15 UTC, soulgchoi requested changes
기능 구현하느라 고생하셨습니다!
hibernate ddl auto 들어간 부분 때문에 체인지 요청 남길게요!
그리고 본문에 첨부한 API 문서만 보면 혼돈되는 부분이 있기 때문에, 이것도 관련해서 논의를 해보았으면 합니다👍

2022-11-02 11:15 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/CouponService.java
> +        }
여기 하나의 메서드에서 
상품 쿠폰 조회 / 카테고리 쿠폰 조회 / 회원이 해당 쿠폰을 쓸 수 있는지 조회 / 회원등급쿠폰 조회
이렇게 총 네 가지의 조회 로직이 있고, 그걸 다시 리스트로 만들고, ...
서로 다른 여러 일을 하고 있어서 메서드 분리하면 좋을 것 같습니다~

2022-11-02 11:15 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/SortWithMaximumDiscountAmount.java
> +    };
이 두 함수는 상수로 만들면 좋을 것 같은데 어떤가요~

2022-11-02 11:15 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/SortWithMaximumDiscountAmount.java
> +                        couponProductResponseDto.getPercentage()));
이 경우에는 최대할인금액을 고려하지 않나요? `Math.max()` 로 묶어주면 할 수 있지 않을까 싶은..

2022-11-02 11:15 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/domain/Coupon.java
> +        return null;
이 `null` 을 어떻게 줄일지... 계속 고민해봅시다......

2022-11-02 11:15 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/ui/CouponController.java
>      @GetMapping("/{productId}")
지금 API 가 GET `/api/coupons/{productId}` 인데, 서버 입장에서는 여기에 `productId` 가 들어간다는걸 알고 있지만 이 정보를 모를 경우에는 특정 쿠폰을 조회하는 API 로 생각되는 것 같아요.
`/api/coupons/products/{productId}` 처럼 상품에 대한 쿠폰인게 표현되면서, 회원 정보도 들어가야 한다는걸 알려주는 API 였으면 좋겠어요.

2022-11-02 11:15 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/ui/CouponController.java
> +    @GetMapping("/product/{productId}")
`product` 를 단수로 표현한 이유가 있나요? 보통 API 는 복수를 많이 쓰는데 이렇게 결정한 이유가 궁금합니다!

2022-11-02 11:15 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/ui/CouponController.java
>          return ResponseEntity.status(HttpStatus.OK).body(couponResponseDtos);
쿠폰은 따로 페이징 안하기로 결정된거죠? 페이지가 있으면 좀 어색할 것 같긴 하네요..

2022-11-02 11:15 UTC, soulgchoi commented on backend/main-service/src/main/resources/bootstrap.yml
> +      ddl-auto: create
develop 브랜치 까지 합쳐지면 dev 새로 빌드할 때마다 테이블 새로 생성할텐데, 이 부분에 대해서는 팀에서 동의가 필요해보이네요!

2022-11-02 11:15 UTC, soulgchoi commented on backend/main-service/src/test/java/kkakka/mainservice/coupon/acceptance/CouponAcceptanceTest.java
> +    private String 일반_쿠폰_생성함2() {
쿠폰 생성 메서드는 `grade`, `productId`, `percentage`, `priceRule` 정도의 값들 빼고는 다 동일한데, 인자로 넣어서 생성할 수 있게 하면 다른 쿠폰 관련 테스트가 추가될 때 재사용성이 훨씬 높아질 것 같아요!
지금의 `일반_쿠폰_생성함` 메서드들은 해당 메서드를 직접 봐야 어떤 쿠폰이 만들어지는지 알 수 있는데, 외부에서 값을 주입하도록 하면 테스트 코드만 봐도 몇 퍼센트 짜리, 어떤 등급에 대한 쿠폰인지 등등 가독성이 높아질거라고 생각합니당

2022-11-02 11:15 UTC, soulgchoi commented on backend/main-service/src/test/java/kkakka/mainservice/coupon/application/CouponServiceTest.java
> +    void 상품_다운가능한_쿠폰_조회() {
왜 얘만 이름이...

2022-11-03 00:15 UTC, omj9803 commented on backend/main-service/src/test/java/kkakka/mainservice/coupon/acceptance/CouponAcceptanceTest.java
> +    private String 일반_쿠폰_생성함2() {
완벽 동의합니다 😅 매개변수로 넣어서 수정하겠습니다!

2022-11-03 00:16 UTC, omj9803 commented on backend/main-service/src/main/resources/bootstrap.yml
> +      ddl-auto: create
빼고 다시 올릴게영..

2022-11-03 00:16 UTC, omj9803 commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/ui/CouponController.java
> +    @GetMapping("/product/{productId}")
상품 하나에 대한 쿠폰들을 조회하는 api 라 단수로 표현했습니당,,

2022-11-03 00:22 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/ui/CouponController.java
> +    @GetMapping("/product/{productId}")
상품 하나는 id 로 충분히 표현이 된다고 생각해서요!
RESTful API 에 대한 참고자료도 많고, 다른 사이트의 API 를 참고하는 것도 좋을 것 같습니다.
https://api.stackexchange.com/docs -> 스택오버플로우의 API
https://restfulapi.net/resource-naming/ -> RESTful API 네이밍 가이드

2022-11-03 01:08 UTC, omj9803 commented on backend/main-service/src/test/java/kkakka/mainservice/coupon/application/CouponServiceTest.java
> +    void 상품_다운가능한_쿠폰_조회() {
헤헤 😆

2022-11-03 01:38 UTC, omj9803 commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/ui/CouponController.java
>      @GetMapping("/{productId}")
@soulgchoi  `/api/coupons/me/products/{productId}` 와 같은 형태는 어떨까요?

2022-11-03 01:39 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/ui/CouponController.java
>      @GetMapping("/{productId}")
오 좋아요👍

2022-11-03 02:29 UTC, omj9803 commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/CouponService.java
> +        }
옙 참고하겠슴니다!

2022-11-03 02:44 UTC, omj9803 commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/SortWithMaximumDiscountAmount.java
> +    };
`final` 선언 하겠슴당 👍🏻

2022-11-03 03:19 UTC, omj9803 commented
@soulgchoi 코드 리뷰 반영했는데 확인 한번 부탁드립니다 !

2022-11-03 03:41 UTC, soulgchoi reviewed
@omj9803 추가로 코멘트 남겼습니다!

2022-11-03 03:41 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/CouponService.java
> +    private void saveCategoryCouponByCategoryId(List<Coupon> coupons, Product product) {
`save` 로 시작하는 메서드가 있어서 쿠폰을 조회하다가 다시 저장하는게 있었나? 라고 생각하고 보니 리스트에 추가하는거였네요. 메서드명이 좀 헷갈릴 수 있을 것 같아요.
그리고 지금같은 메서드 분리 방식은 `showCouponsByProductId` 에 있는 `coupons` 를 변경하는 것이기 때문에, 여기서 따로 리스트를 반환한 뒤에 `showCouponsByProductId` 에서 add 하는 편이 좋을 것 같습니다!

2022-11-03 03:41 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/CouponService.java
> +        if (product.getCategory() != null) {
카테고리가 `null` 이 아닐 때 카테고리 쿠폰을 검색하는데 이 부분이 `showCouponsByProductId` 에서는 알 수 없고, 마치 이 메서드를 수행하면 카테고리 유무에 관계없이 카테고리 쿠폰을 저장하는 것처럼 보이지 않을까요..?

2022-11-03 03:41 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/SortWithMaximumDiscountAmount.java
> +            couponProductResponseDto.saveDiscountedPrice(
이미 만든 dto 를 또 변경하지 않는 방법은 없을까요. dto 생성 시 `discountPrice` 를 계산하고 정렬만 그 기준으로 한다거나..

2022-11-03 03:41 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/CouponService.java
> +                    CouponProductResponseDto.create(memberCoupon.getCoupon(), false));
메서드는 `checkUnusedGradeCouponByMemberId` 인데 dto 생성까지 하고 있다는건 메서드가 의도한것 외의 역할까지 추가로 수행하고 있는게 아닐까요..!

2022-11-03 03:45 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/SortWithMaximumDiscountAmount.java
> +            couponProductResponseDto.saveDiscountedPrice(
지금도 뭐.. 괜찮은거 같긴 한데 개인적인 생각으로는
`쿠폰을 찾아온다 -> dto 로 만든다 -> 정렬한다 -> 할인 금액을 계산해서 넣는다 -> 반환한다` 이거보다는
`쿠폰을 찾아온다 -> 할인 금액을 계산한다 -> dto 로 만든다 -> 정렬해서 반환한다` 이 편이 더 자연스럽게 느껴져서 다른 의견을 듣고싶습니다!

2022-11-03 03:48 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/SortWithMaximumDiscountAmount.java
> +            couponProductResponseDto.saveDiscountedPrice(
coupon 이나 product 에 따로 쿠폰 적용 금액에 대한 값이 없고 dto 에만 추가되므로, `할인 금액을 계산한다`, `정렬한다` 이런 로직은 완전히 별개로 추가되어서 dto 를 생성한다고 생각할 수 있을 것 같아서요! 느낌이 잘 표현이 안되는데 좀 분리된 부분이다 라는 그런 말이었습니다....

2022-11-03 05:16 UTC, omj9803 commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/CouponService.java
> +                    CouponProductResponseDto.create(memberCoupon.getCoupon(), false));
흠 `checkUnusedGradeCouponByMemberId` 가 쓰지않은 등급쿠폰을 확인해서 있다면 dto 에 넣어주는 역할인데 그럼 메소드 분리를 안하는게 나을까요 😅

2022-11-03 05:19 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/CouponService.java
> +                    CouponProductResponseDto.create(memberCoupon.getCoupon(), false));
쓰지 않은 등급 쿠폰만 확인 및 반환하면 안되나요?

2022-11-03 05:25 UTC, omj9803 commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/CouponService.java
> +                    CouponProductResponseDto.create(memberCoupon.getCoupon(), false));
`MemberCoupon` 에서 `isUsed` 가 `false` 인 쓰지 않은 등급 쿠폰만 찾아와서 dto 에 넣어주는 코드입니닷

2022-11-03 05:57 UTC, omj9803 commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/SortWithMaximumDiscountAmount.java
> +            couponProductResponseDto.saveDiscountedPrice(
저도 sort 에서 할인 금액을 계산하는게 맞는지 의문이었어서 분리된 부분이라는 의견에 동의합니다! 그런데 그럼 dto 생성 시 product 의 가격을 넘겨줘서 할인 금액을 계산해야 하는데 dto 에 넘겨주는게 맞는지 헷갈리네요 😅 복잡...

2022-11-03 06:30 UTC, omj9803 commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/CouponService.java
> +    private void saveCategoryCouponByCategoryId(List<Coupon> coupons, Product product) {
`save` 대신 `find` 로 수정하겠습니다!

2022-11-03 07:19 UTC, omj9803 commented
@soulgchoi @tlsdnwn55 @zihuns @devpoooh 머지하고싶어요.. 어푸르브 내나...

2022-11-03 07:30 UTC, zihuns approved these changes

2022-11-03 07:46 UTC, soulgchoi reviewed
중간에 제 의도가 잘못 전해진 것 같아서 추가 코멘트 남겼습니다!
무조건 반영해달란 말은 아니고요, 저는 dto 는 데이터 전송 객체일 뿐이라 여기에 별도 로직을 넣지 않으려고 하는 편이고 되도록이면 서비스 레이어에서 수행하거든요. 어떻게 책임을 분리하면 좋을지 생각한 바가 있다면 그걸 코드에 표현해주시고, 의견 말해주면 저도 오케이하겠습니다!

2022-11-03 07:46 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/ui/dto/CouponProductResponseDto.java
> +    };
제 의도는 dto 는 순수하게 데이터 전달만 하고 service 에서 할인 금액 계산 같은 비즈니스 로직을 수행했으면 하는거였는데 의도가 잘못 전달된 것 같아요ㅎㅎ 다른 생각이 있다면 궁금합니다

2022-11-03 07:46 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/SortWithMaximumDiscountAmount.java
> +public class SortWithMaximumDiscountAmount {
지금 상태에서 정렬 클래스를 분리하는 의미가 있을까요..? 그냥 return 할 때 해도 될거같기도 하고요
이대로 별도 유틸리티처럼 사용해서 이점이 있다고 생각한다면 그대로 두어도 좋을 것 같습니다!

2022-11-04 05:54 UTC, soulgchoi approved these changes

2022-11-04 06:02 UTC, omj9803 commented
다른 곳에서 재사용하려나 싶어서 클래스로 빼뒀던 `sort` 부분을 dto 를 사용하는 부분이 상품 쿠폰 확인하는 부분밖에 없어서 `CouponService` 에 넣었습니다. 저도 dto는 데이터 전달만 하는 거라는거에 동의해서 할인 금액 계산하는 로직을 service 단으로 뺐는데 service 단에서 하는 일이 많아졌네용 😅 추후에 코드 정리에 대한 의견 있으시면 반영하겠습니다 
@soulgchoi @devpoooh @zihuns @tlsdnwn55

2022-11-04 06:11 UTC, soulgchoi approved these changes
dto 생성 + 계산 + 정렬이 지금은 변경하려면 좀 많은 수정을 거칠 것 같네요. 고생하셨습니다!

2022-11-04 06:11 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/CouponService.java
> +    };
요거는 메서드가 아니라 변수로 선언한거니까 위로 올리면 좋겠어요!

2022-11-04 06:16 UTC, soulgchoi commented
@omj9803 변수 선언 위치에 대한 코멘트를 달았다가 삭제했는데,
저는 보통 메서드 위에 필요한 변수들을 선언하는 편이었는데 `클린 코드`에서도 그렇고 [이 글](https://okky.kr/articles/750617)에서도 메서드와 가깝게 위치하도록 권하고 있네요!
그동안 클래스가 작아서 최상위에 선언해도 괜찮았는데... 지금은 서비스 클래스가 길어서 가까이에 있는것이 가독성 면에서 좋은것 같아요!

2022-11-04 06:57 UTC, merged