feat: 장바구니 아이템 수 표시, 리뷰 더보기 구현
LOTTE-5IVE/kka-kka pull request #209
Opened 2022-11-08 06:09 UTC by zihuns

## Resolve #207 #208 

### 설명
- 장바구니에 담긴 아이템 수가 표시되도록 하였습니다.
- 리뷰 줄 수 기준으로  더보기를 구현했습니다.
- 검색결과 없을 시 나타나는 페이지 구현했습니다.
- snake case -> camel case로 변경되지 않았던 남은 부분 수정했습니다.

2022-11-08 07:33 UTC, soulgchoi commented
![스크린샷 2022-11-08 오후 4 33 01](https://user-images.githubusercontent.com/52682603/200501868-3cf5da13-21b9-49b4-b408-48004e7ea2bf.png)
주문내역 들어갔을 때 에러나요ㅠㅠ

2022-11-08 07:43 UTC, soulgchoi requested changes
에러 때문에 화면 확인이 안돼서.. 해결 부탁합니다~!!

2022-11-08 07:43 UTC, soulgchoi commented on frontend/components/mypage/MyOrderTemp.js
`MyOrderTemp` 는 이제 temp 떼고 이름을 주면 좋지 않을까요ㅎㅎ

2022-11-09 01:34 UTC, soulgchoi commented
> 에러 때문에 화면 확인이 안돼서.. 해결 부탁합니다~!!

확인했습니다~!

2022-11-09 01:44 UTC, soulgchoi approved these changes
고생하셨습니다~ 검색 결과 없을 때 페이지 궁금한데 빨리 적용되면 좋겠네요~!

2022-11-09 01:51 UTC, devpoooh approved these changes
👍

2022-11-09 02:11 UTC, soulgchoi reviewed
approve 를 남기긴 했으나.. 몇가지 오류가 발견되어 코멘트 추가로 남깁니다...
#215 이거 제가 해결한줄 알았으나 상황에 따라 동일한 문제가 또 발생하네요. 직접 확인해주시면 좋을 것 같아요~!

2022-11-09 02:11 UTC, soulgchoi commented on frontend/components/common/HeaderComp.js
> +
검색한 페이지에서 다시 검색어 입력하면 새로 검색이 안되네요~!

2022-11-09 02:11 UTC, soulgchoi commented on frontend/components/common/HeaderComp.js
>    function search(event) {
해당 함수 호출하는 부분(84번 라인)에서는 `value` 도 넘기는데 여기는 사용하지 않네요!

2022-11-09 05:11 UTC, merged