feat: 장바구니 추가,조회,삭제 기능 구현
LOTTE-5IVE/kka-kka pull request #29
Opened 2022-09-27 04:59 UTC by tlsdnwn55

## Resolve #16 #21 

### 설명
- 장바구니 추가,조회,삭제 기능을 구현하였습니다.
- 각각 동일한 API에 Post,Get,Delete 메소드로 처리하였습니다.
- Member 객체를 컨트롤러에서 어떻게 전달받을지 논의가 필요합니다.
- 테스트 코드를 작성하였습니다.

2022-09-27 06:41 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
> +@RequestMapping("/carts")
제 생각에는
- GET `/carts/{cartId}`
- POST `/carts`
- DELETE `/carts/{cartId}`
이렇게 만드는게 더 restful 하지 않나 싶네요ㅎㅎ

2022-09-27 06:42 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(responseDto);
201 created 가 body 를 반환해줄까요?
Location 정보를 주는게 보편적인 것으로 알고있어요 ㅎㅎㅎ

2022-09-27 06:43 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
> +        /* 멤버 객체 어떻게 전달 받을지 생각해보기 */
주석 작성할 때 `TODO:` 붙여서 쓰면 인텔리제이가 잘 트래킹해줍니다~!
팀원들이랑 같이 볼 때도 훨씬 좋겠죵!

2022-09-27 06:43 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
> +        return ResponseEntity.status(HttpStatus.OK).body("success");
200 OK 인데 success 라고 메시지를 따로 줄 필요가 없을까요? 이미 요청이 성공했으니 충분해 보이는데요ㅎㅎ

2022-09-27 06:44 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/common/config/WebConfig.java
> +            p.setMaxPageSize(5);
이거 전에도 제가 뭔지 물어봤었는데.. 좀 더 분명한 이름으로 작성해주시면 좋을 것 같습니다!

2022-09-27 06:45 UTC, soulgchoi commented on backend/main-service/src/test/java/kkakka/mainservice/cart/ui/CartAcceptanceTest.java
> +    @Order(1)
테스트 순서가 달라졌을 때 실패한다면 좋은 테스트라고 할 수 있을까요?
상품을 조회하려면 반드시 추가가 성공해야 할까요? 그냥 DB에 있기만 해도 조회는 할 수 있을 것 같은데요.

2022-09-27 06:50 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +            cartItemRepository.updateCartItemQuantity(cartRequestDto.getQuantity(), item.getId());
JPA는 update 쿼리를 직접 작성하지 않아도 알아서 쿼리를 잘 날려준답니닷
아래 제가 작성한 테스트인데 참고하시고 영속성 컨텍스트에 대해 좀 더 공부해보면 좋을 것 같아요!

```java
@DataJpaTest
public class CartRepositoryTest {

    @Autowired
    CartItemRepository cartItemRepository;
    @Autowired
    CartRepository cartRepository;
    @PersistenceContext
    EntityManager em;

    @DisplayName("이미 카트에 있는 아이템 수량 업데이트")
    @Test
    void updateCartQuantity() {
        // given
        final Cart cart = new Cart(TestDataLoader.MEMBER);
        cartRepository.save(cart);
        em.flush();

        final CartItem cartItem = new CartItem(cart, PRODUCT_1, 1);
        final CartItem originCartItem = cartItemRepository.save(cartItem);
        em.flush();

        // when
        final CartItem quantityModifiedCartItem = new CartItem(originCartItem.getId(), cart, PRODUCT_1, 3);
        final CartItem updatedCartItem = cartItemRepository.save(newCartItem);
        em.flush();

        // then
        final Optional<CartItem> savedCartItem = cartItemRepository.findById(
                originCartItem.getId());
        assertThat(savedCartItem.get().getQuantity()).isEqualTo(updatedCartItem.getQuantity());
    }
}
```

2022-09-27 06:51 UTC, soulgchoi requested changes
코드리뷰 더 길어질 것 같아서 보이는 부분만 우선 남길게요..
http status 201 주는 부분이랑, cartItem update에 관해서 코멘트 남겼는데 제가 남긴 의견 + 개인적인 생각으로 코드를 작성해보면 service 로직이

```java

2022-09-27 07:13 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
> +@RequestMapping("/carts")
- GET /carts/{cartId} 로 하면 클라이언트에서 내 장바구니 접속할 때부터 cartId를 들고있어야 요청가능할거 같은데 뭔가 부자연스럽지 않을까요? 저는 로그인한 멤버라면 Member 객체를 전달받아 조회할 생각이였습니다 ..

2022-09-27 07:15 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(responseDto);
잘 모르는 부분이였는데 감사합니다 그런데 장바구니 추가는 보통 추가하고나면 계쇽 쇼핑 하시겠습니까? or 장바구니 이동하기 물어보는 경우가 많더라구요 이 부분은 어떻게 할지 ??

2022-09-27 07:15 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
> +        /* 멤버 객체 어떻게 전달 받을지 생각해보기 */
넵 ~!

2022-09-27 07:16 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
> +        return ResponseEntity.status(HttpStatus.OK).body("success");
넵넵

2022-09-27 07:16 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/common/config/WebConfig.java
> +            p.setMaxPageSize(5);
넵 고치겠슴다 ㅜ

2022-09-27 07:22 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +            cartItemRepository.updateCartItemQuantity(cartRequestDto.getQuantity(), item.getId());
이 부분 티아카데미 강의 들으면서 저도 생각나서 반영할라 했는데 JpaRepository 만 쓰다보니 EntityManger를 어떻게 가져와서 써야할지 몰라서 그냥 JPQL로 처리했네요
@PersistenceContext
    EntityManager em; 이런식으로 가져올 수 있군용

2022-09-27 07:23 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(responseDto);
Location 으로 장바구니 id를 넘겨주고 리다이렉트하게 처리할 수 있을거 같네용~!

2022-09-27 07:27 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +            cartItemRepository.updateCartItemQuantity(cartRequestDto.getQuantity(), item.getId());
테스트 하려고 일부러 EntityManager 불러왔는데 flush 하지 않고 실행하면 update 없이 최종 save 쿼리 한 번만 나갈거예요~~
한 트랜잭션 안에서 엔티티 생성, 수정 -> 1차 캐시에 쌓임 -> 최종 상태는 수정된 entity 하나만 있으면 됨 -> save 쿼리 하나만 있으면 되기 때문임다
암튼 `when` 부분처럼 찾아온 `CartItem` 아이디를 가지고 저장하면 동일한 엔티티일 경우 save 수행시 update 시킵니닷
(이 때 `CartItem`은 equals & hashcode 로 id 기준으로 동등성, 동일성 비교하게 설정해두었음)

2022-09-27 07:27 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
> +@RequestMapping("/carts")
네 저도 이거 좋은거 같아여~~~~😉

2022-09-27 07:45 UTC, zihuns approved these changes

2022-09-27 08:17 UTC, tlsdnwn55 commented on backend/main-service/src/test/java/kkakka/mainservice/cart/ui/CartAcceptanceTest.java
> +    @Order(1)
테스트코드는 좀 더 공부를 하겠습니다 ㅜ.ㅜ

2022-09-28 07:28 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
>          Optional<Member> member = memberRepository.findById(cartRequestDto.getMemberId());
`Member` 없을 때 처리도 한 번 고민해주세요~ `Optional` 안의 값이 `null` 이라면 아래에서 NPE가 발생하겠네요.
위에서 미리 검증을 해주는게 필요해보여요!

2022-09-28 07:31 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +            cartItemRepository.save(cartItem.get());
```suggestion
            CartItem originCartItem = cartItem.get();
            Integer preQuantiry = originCartItem.getQuantity();
            originCartItem.setQuantity(preQuantiry + cartRequestDto.getQuantity());
            cartItemRepository.save(originCartItem);
```
여러 번 사용하는 변수라 따로 선언해도 좋을 것 같아요!
그리고, 장바구니 수량이 바뀌면 더해야할까요 아니면 변경을 해야할까요.. 
이건 정책적인 부분이라 생각을 해봐야겠지만, 장바구니 최초 추가 + 변경에 같은 API를 사용하고 있으니 변경이 더 자연스러운 로직이 아닐까 생각이 되네요!!

2022-09-28 08:21 UTC, soulgchoi reviewed
피드백 반영하느라 고생하셨습니다!
비즈니스 로직에 대한 의견을 듣고싶어서 approve 는 한 번 더 미루겠습니다..👍

2022-09-28 08:21 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +            cartItemRepository.save(cartItem.get());
```suggestion
            CartItem originCartItem = cartItem.get();
            Integer preQuantiry = originCartItem.getQuantity();
            originCartItem.setQuantity(preQuantiry + cartRequestDto.getQuantity());
            cartItemRepository.save(originCartItem);
```
여러 번 사용하는 변수라 따로 선언해도 좋을 것 같아요!

그리고, 장바구니 수량이 바뀌면 더해야할까요 아니면 변경을 해야할까요.. 
이건 정책적인 부분이라 생각을 해봐야겠지만, 장바구니 최초 추가 + 변경에 같은 API를 사용하고 있으니 변경이 더 자연스러운 로직이 아닐까 생각이 되네요!!

2022-09-28 08:21 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
>          Optional<Member> member = memberRepository.findById(cartRequestDto.getMemberId());
Member 없을 때 처리도 한 번 고민해주세요~ Optional 안의 값이 null 이라면 아래에서 NPE가 발생하겠네요.
위에서 미리 검증을 해주는게 필요해보여요!

2022-09-28 08:21 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +        cartItemRepository.save(cartItem.get());
위에 있는 `Optional<CartItem> cartItem` 에 재할당을 한다면 좀 헷갈리지 않을까요?
새로 선언하는 편이 좋아보입니다!

여기서는 이미 `new CartItem(...)`을 하고 있기 때문에 `null` 값이 생성되지 않으므로 `Optional.ofNullable`로 받을 필요 없이 바로 `CartItem`으로 받을 수 있겠어요.
그렇다면 `get()` 하는 부분 없이 바로
```java
cartItemRepository.save(new CartItem(cart, product.get(), cartRequestDto.getQuantity()));
```
이렇게 저장할 수도 있겠네요!

그리고 `product.get()` 하는 부분도 NPE가 발생할 수 있으니 처리할 필요가 있어보입니다~

2022-09-28 08:21 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +
```suggestion
```

2022-09-28 08:21 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +        });
스트림을 활용해보아요😉 저라면 바로 리턴할 것 같아요.

```suggestion
        List<CartItem> cartItemList = cartItemRepository.findAllByMemberId(member.getId());
        
        return cartItemList.stream()
                      .map(cartResponseDto::from)
                      .collect(Collectors.toList());
```

2022-09-28 08:21 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +        });
for 문을 사용하면 확실히 누구나 알아볼 수 있는 가독성이 생기죠.
하지만 스트림도 잘 활용한다면 충분히 가독성 좋고 단순한 코드를 만들 수 있다고 생각합니다!ㅎㅎ

2022-09-28 08:21 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +        cartItemRepository.deleteCartItemById(cartItemId);
JpaRepository 가 기본적으로 `deleteById` 메서드를 지원해주지 않나요? `cartItemId`가 PK라서 바로 될 것 같아요.
아니면 지송..🥲

2022-09-28 08:21 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +        return cartRepository.findByMemberId(member.getId()).orElseGet(() -> createCart(member));
```suggestion
        return cartRepository.findByMemberId(member.getId())
                      .orElseGet(() -> createCart(member));
```

저는 이런거 개행 한번 해주면 가독성이 훨 좋아보이더라구요!

2022-09-28 08:21 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
>      }
클래스 상단에 `@RequiredArgsConstructor` 롬복 어노테이션을 사용할 수도 있을 것 같은데요!
직접 생성자 작성하는게 더 좋아서 이렇게 선택했다면 저는 그거대로 납득입니다.
그래도 이왕 쓰는거 쉽게쉽게 코드 작성하면 좋으니까요🫠

2022-09-28 08:21 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
> +        return ResponseEntity.created(location).build();
```suggestion
        Long memberId = cartService.saveOrUpdateCartItem(cartRequestDto);
        return ResponseEntity.created(URI.create(memberId.toString())).build();
```
```suggestion
        Long memberId = cartService.saveOrUpdateCartItem(cartRequestDto);
        return ResponseEntity.created(URI.create(String.format("/%d", memberId))).build();
```

이런식으로 static 메서드를 활용해도 될 것 같습니다~

2022-09-28 08:21 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/product/ui/ProductController.java
>          return ResponseEntity.status(HttpStatus.OK).body(result.getContent());
페이지 정보도 주도록 response 형식을 계속 고민해봐야할 것 같네요~

2022-09-28 08:21 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/common/config/WebConfig.java
> +            pageSizeConfig.setMaxPageSize(5);
최고최고👍👍👍👍

2022-09-28 08:21 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/product/domain/Product.java
> +import com.fasterxml.jackson.annotation.JsonIgnore;
사용 안하는 import 문 제거해주세요!

2022-09-28 08:21 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
> +        });
`cartService` 에 리스트를 주지 않고 메서드를 여러번 호출하는 이유는 뭔가요?
순수한 의문입니다..

2022-09-28 08:27 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +            cartItemRepository.save(cartItem.get());
저도 생각해보니 그냥 새로운 수량으로 변경을 하는게 로직이 훨씬 자연스러울거 같아요 
변수도 처리하겠습니다 !

2022-09-28 08:29 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +        cartItemRepository.save(cartItem.get());
반박여지가 없습니다! 모든 의견 반영하겠습니다 감사합니다

2022-09-28 08:32 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
>          Optional<Member> member = memberRepository.findById(cartRequestDto.getMemberId());
이 부분은 멤버검증 로직이 추가된다면 저는 컨트롤러에서 Member 검증을 하고
로그인한 멤버라면 서비스단으로 넘길 생각이였는데 그래도 NPE가 발생할까요??
잘몰라서 질문드립니다 ~!

2022-09-28 08:35 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +        });
Optional 도 그렇고 스트림도 그렇고 잘 알면 가독성도 좋고 코드도 더 개발자스럽고 좋아보여요
예시가 있으면 활용할 수는 있겠는데 아직 머리속에 자리잡지 않아서 바로바로 안떠오르네요
이것도 반영하도록 하겠습니다 ~! 감사

2022-09-28 08:35 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +        return cartRepository.findByMemberId(member.getId()).orElseGet(() -> createCart(member));
반영하겟습니다 ~!

2022-09-28 08:35 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
>      }
정신없이 하다보니 통일이 안되었습니다 바로 수정할게용

2022-09-28 08:44 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +        cartItemRepository.deleteCartItemById(cartItemId);
되는거같아요 ㅎㅎ;

2022-09-28 09:00 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
> +        });
아무 생각없이 코딩해서 그렇습ㄴ디ㅏ 수정했습니다

2022-09-28 09:00 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/product/domain/Product.java
> +import com.fasterxml.jackson.annotation.JsonIgnore;
넵넵

2022-09-28 09:05 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
> +        return ResponseEntity.created(location).build();
ServletUriComponentsBuilder.fromCurrentRequest() 가 없어서 저대로 하면 Location: /1 이 반환되는데 .... 어떻게 해야할까요

2022-09-28 09:15 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
> +        return ResponseEntity.created(location).build();
다시 보니 ServletUriComponentsBuilder 그대로 쓰는거 좋습니다!👍

2022-09-28 09:20 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
>          Optional<Member> member = memberRepository.findById(cartRequestDto.getMemberId());
저도 토큰에서 가져오는 Member 는 어느 정도 검증이 되었다고 생각하는데요~ 
대신 토큰이 발급된 시점과 요청하는 시점 사이에 데이터 정합성이 보장되느냐의 관점에서 보면 최소한의 에러 핸들링은 필요하지 않을까 싶네요!

2022-09-29 02:50 UTC, soulgchoi reviewed
어제 못봤던거 추가로 코멘트 남겼어요ㅎㅎ
그리고 다른 코드 보다보니까 `테스트를 위한 코드` 라는 주석이 붙은 메서드가 있었는데요,
우리 서비스 전체 비즈니스 로직과 관련없이 정말 테스트를 위해서만 만들어야 하는 메서드라면.. 그런 환경이 필요한 테스트가 잘못된건 아닐까 생각해볼만한 문제라고 여겨지네요!

그리고 서비스 레이어에 주석이 많은 메서드가 하나 있었는데, 
주석을 달아야만 어떤 행위인지 표현할 수 있다면 주석보다는 메서드를 분리해서 좀 더 명확한 이름을 부여하는게 좋을것 같다는 생각입니다😉

2022-09-29 02:50 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/dto/CartResponseDto.java
> +@Setter
setter... 꼭 있어야 하나요...?

2022-09-29 02:50 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/dto/CartResponseDto.java
> +    private Integer totalPrice;
이렇게 데이터 펼쳐서 줄 수도 있지만,
```json
{
  "id": "id",
  "cartItem": [
  {
      "id": "id",
      "product": {
        "id": "id",
        "name": "name",
        "price": "price",
      },
      "quantity": "quantity",
      "totalPrice": "totalPrice"
    },
   {
      "id": "id",
      "product": {
        "id": "id",
        "name": "name",
        "price": "price",
      },
      "quantity": "quantity",
      "totalPrice": "totalPrice"
    }
  ]
}
```
이렇게 생길 수도 있지 않을까요.. 이건 프론트랑도 잘 소통해서 만들 수 있을 것 같아요.
현재 코드는 장바구니 아이템 리스트를 반환할 때 장바구니-아이템-상품 하나씩 있는 리스트를 반환하겠네요..

2022-09-29 02:50 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
> +    @PostMapping("/cart")
장바구니에 생성하는 요청 API 가 그럼 `/carts/cart`가 되나요?
이 때 `carts` 랑 `cart` 는 다른 자원을 표현하기 때문에 따로 쓴건가요? 라고 생각하기엔 delete는 `/carts/cart/{id}`가 아니라 `/carts/{id}` 로 사용하고 있네욤..
이렇게 구성한 의도가 있다면 설명 plz

2022-09-29 02:50 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
> +        cartService.deleteCartItem(cartItemList);
메서드명 `deleteCartItems()` 복수로 쓰는게 더 좋을거 같아요ㅎㅎ 하나 삭제할거 같은 느낌

2022-09-29 02:50 UTC, soulgchoi commented on backend/main-service/src/test/java/kkakka/mainservice/cart/ui/CartAcceptanceTest.java
> +//                .queryParam("memberId",member.getId())
테스트 하면서 바꿔봤던건가요?ㅎㅎ 주석은 지워도 될거같아여

2022-09-29 02:50 UTC, soulgchoi commented on backend/main-service/src/test/java/kkakka/mainservice/cart/ui/CartAcceptanceTest.java
> +    }
삭제 테스트는 조회 요청을 한번 더 보내서 정상 삭제되어 조회할 수 없는지 케이스도 추가로 테스트하면 좋을거 같아요ㅎㅎㅎ

2022-09-29 04:51 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
> +    @PostMapping("/cart")
소통의 오류가 있었던거 같아요 ...

2022-09-29 05:13 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/CartController.java
> +        cartService.deleteCartItem(cartItemList);
넵!

2022-09-29 05:13 UTC, tlsdnwn55 commented on backend/main-service/src/test/java/kkakka/mainservice/cart/ui/CartAcceptanceTest.java
> +//                .queryParam("memberId",member.getId())
넵!

2022-09-29 05:13 UTC, tlsdnwn55 commented on backend/main-service/src/test/java/kkakka/mainservice/cart/ui/CartAcceptanceTest.java
> +    }
넵넵 !

2022-09-29 05:17 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/dto/CartResponseDto.java
> +@Setter
바로지웠습니다

2022-09-29 05:17 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/dto/CartResponseDto.java
> +    private Integer totalPrice;
제가 생각했던건 Cart 안에 List<CartItem> 이 있고 CartItem 1개당 Product 1개가 들어있는 구조인데
회원은 장바구니를 2개이상 가질 수 없고 단방향 매핑만 설정해둬서 CartItemRepository에서 Cart-Member 테이블과 조인해서 가져오는 방식입니다
[
    {
        "cartId": 1,
        "cartItemId": 1,
        "productId": 1,
        "productName": "롯데 제로 초콜릿칩 쿠키 168g",
        "imageUrl": "https://user-images.githubusercontent.com/99088509/191633507-6280963f-6363-4137-ac2a-a8a060d28669.png",
        "coupon_id": null,
        "quantity": 3,
        "price": 4480,
        "totalPrice": 13440
    },
    {
        "cartId": 1,
        "cartItemId": 2,
        "productId": 2,
        "productName": "롯데 제로 초콜릿칩 쿠키 168g",
        "imageUrl": "https://user-images.githubusercontent.com/99088509/191633507-6280963f-6363-4137-ac2a-a8a060d28669.png",
        "coupon_id": null,
        "quantity": 3,
        "price": 4480,
        "totalPrice": 13440
    },
    {
        "cartId": 1,
        "cartItemId": 3,
        "productId": 3,
        "productName": "롯데 제로 초콜릿칩 쿠키 168g",
        "imageUrl": "https://user-images.githubusercontent.com/99088509/191633507-6280963f-6363-4137-ac2a-a8a060d28669.png",
        "coupon_id": null,
        "quantity": 3,
        "price": 4480,
        "totalPrice": 13440
    }
]
현재 이렇게 반환되네요 어떻게 생각하시는지 의견 피드백 주세요 ~!

2022-09-29 06:40 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/ui/dto/CartResponseDto.java
> +    private Integer totalPrice;
서버에서 데이터 가져올땐 이렇게 되겠지만 API 를 구현한다는 시점에서 보면 API 는 결국 자원의 표현이잖아요?
응답받는 사용자(우리의 사용자는 프론트엔드 개발자)에게 자원이 어떻게 구성되어 있다는 것을 더 잘 표현할 수 있는 방향으로 만들면 좋겠다는게 제 생각입니다.
`제가 생각했던건 Cart 안에 List 이 있고 CartItem 1개당 Product 1개가 들어있는 구조인데` 저도 이 구조가 맞다고 생각하거든요. 그렇다면 Cart > CartItem + Product 리스트 이대로 표현될텐데.. 지금 응답값 같은 경우에는 Cart를 요청했는데 CartItem 중심적인 데이터, 즉 서버에서 가져오기 쉬운 구조를 그대로 반환한다고 보일 수도 있을거 같아요~

2022-10-06 06:30 UTC, omj9803 commented on backend/main-service/src/main/java/kkakka/mainservice/common/config/WebConfig.java
> +            pageSizeConfig.setMaxPageSize(2);
good!!J!! 👍🏻

2022-10-06 06:32 UTC, omj9803 commented on backend/main-service/src/test/java/kkakka/mainservice/cart/ui/CartAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.OK.value());
오 테스트 response 상태와 비교하는거네용! 배워갑니당

2022-10-07 02:41 UTC, tlsdnwn55 commented
@soulgchoi 진짜 다 된거같습니다 확인점요

2022-10-07 02:50 UTC, zihuns approved these changes

2022-10-07 07:54 UTC, tlsdnwn55 commented
@soulgchoi  If there is no problem, can I merge?

2022-10-07 07:54 UTC, soulgchoi approved these changes
👍

2022-10-07 07:56 UTC, merged