Feat: 상품 주문 구현
LOTTE-5IVE/kka-kka pull request #31
Opened 2022-09-27 07:25 UTC by devpoooh

## Resolve #26 

### 설명
- 주문 엔티티, 상품주문 엔티티 연관관계를 구현하였습니다.
- 여러 상품 주문 서비스 개발을 하였습니다. 
   - memberId, productId, count 정보를 넘겨받아 주문 엔티티를 생성합니다.
- 테스트 코드를 작성하였습니다.

### 기타
- 테스트 코드의 경우 작성중에 있습니다.
- 주문상품의 수량, 상품의 재고관리 로직 구현이 필요합니다.
- 주문이 가지고 있어야 할 배송정보 부분 로직 구현이 필요합니다.

2022-09-27 08:06 UTC, zihuns approved these changes

2022-09-27 08:34 UTC, tlsdnwn55 reviewed
테스트는 제가 잘 몰라서 모르겠네요 저와 마찬가지로 많은 수정을 하실듯 합니다 ㅎㅎ

2022-09-27 08:34 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/order/ui/OrderController.java
> +        return "주문저장 성공"+order;
OrderRequestDto 를 만들어서 @Requestbody로 처리하는게 더 좋지 않을까 생각합니다 !

2022-09-27 08:34 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/order/domain/ProductOrder.java
> +    private int count; //주문수량
이거 솔지누나가 Integer 로 해달랬어요 ~!

2022-09-27 08:34 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/member/domain/Member.java
> +
멤버까지 양방향조인해서 쓸일이 있을까 싶은데 저도 햇갈려서 밑에 분이 아실거같아용
order에서 멤버 id만 조인하면 되지 않을까?? 싶은 ..

2022-09-27 09:11 UTC, devpoooh commented on backend/main-service/src/main/java/kkakka/mainservice/member/domain/Member.java
> +
회원이 주문한 주문 리스트를 가져야한다고 생각해서 양방향관계로 했는데 주문 리스트가 필요없는 경우라면 다시 고려해볼게요.

2022-09-27 09:12 UTC, devpoooh commented on backend/main-service/src/main/java/kkakka/mainservice/order/ui/OrderController.java
> +        return "주문저장 성공"+order;
controller부분은 아직 테스트였는데 올라갔네요...ㅎ dto처리로 수정해보겠습니다.

2022-09-27 09:12 UTC, iamhyeyeon commented on backend/main-service/src/main/java/kkakka/mainservice/order/domain/ProductOrder.java
> +    private int count; //주문수량
네 반영하겠습니다~

2022-09-28 09:16 UTC, soulgchoi requested changes
복잡한 기능인데 고생하셨습니다👍
OOP랑 트랜잭션 관련해서 좀 더 봤으면 하는 마음이 드네요!
로직 자체는 좋습니다!

2022-09-28 09:16 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/member/domain/Member.java
> +
조인해서 가져오는 성능이 너무 안좋으면 양방향으로 만들 수 있지만 지금은 모두 단방향으로 처리하고 가는게 좋을 것 같아요~~
JPA 이렇게저렇게 써보는 학습 관점에서ㅎㅎ

2022-09-28 09:16 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/order/application/OrderService.java
> +@Transactional
클래스 레벨에서 `@Transactional` 선언했을 때 문제는 없을지 생각해보아요

2022-09-28 09:16 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/order/application/OrderService.java
> +     */
이렇게 딱 봐도 주문인 메서드는 주석 굳이 붙이지 않아도 된다고 생각합니다~
갠적으로 주석 지양하고 글처럼 읽히는 코드를 선호하는 편이라 개인 취향입니닷ㅎㅎ

2022-09-28 09:16 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/order/application/OrderService.java
> +    public Long order(Long memberId, List<Long> productIds, int count) {
`order` 메서드 안에서 여러 일을 하고 있는데요, 주석으로 각각 어떤 코드인지 구분해야 한다면 메서드 분리해서 메서드명으로 로직을 표현하는게 더 좋지 않을까요?

그리고 `@Transactional` 어노테이션을 중복해서 작성했는데,
트랜잭션이 어떻게 작동하는지 스프링의 트랜잭션을 찾아보는걸 추천합니다~

2022-09-28 09:16 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/order/domain/Order.java
> +    private Member member; //주문회원
이런 주석은 없어도 될 것 같습니다!

2022-09-28 09:16 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/order/domain/Order.java
> +    public static Order createOrder(Member member, int totalPrice, List<ProductOrder> productOrders) {
`create` 라는 이름으로 충분히 행위를 표현할 수 있을거라는 생각이 드네용ㅎㅎ
`Order.create()`, `ProductOrder.create()` 이런 식으로 쓰게 되니까요

2022-09-28 09:16 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/order/domain/Order.java
> +        return order;
```suggestion
      new Order(null, member, LocalDateTime.now(), productOrders, totalPrice);
```

모든 필드를 매개변수로 가지는 주생성자를 만들고 위처럼 표현하면 더 좋을 것 같아요.
setter 를 꼭 써야하는 게 아니라면 최대한 쓰지 않고 싶어서요.

왜 객체지향 프로그래밍에서 setter 를 지양하는지 찾아보는거 추천!

2022-09-28 09:16 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/order/domain/Order.java
> +    }
```suggestion
    public int getTotalPrice() {
        return productOrders.stream()
                .mapToInt(ProductOrder::getTotalPrice)
                .sum();
    }
```

스트림을 써보는건 어떤가요! 지금 메서드도 충분히 가독성이 좋지만, `sum` 이라는 단어로 표현해주는 뉘앙스가 있잖아요?
이런 방식도 있다는 것ㅎㅎㅎ

2022-09-28 09:16 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/order/domain/Order.java
> +    }
위에 남긴 코멘트처럼 Order 생성 메서드를 변경한다면 필요없어지겠네요😉

2022-09-28 09:16 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/order/domain/ProductOrder.java
> +    //주문 상품, 가격, 수량 정보를 사용해서 주문상품 엔티티 생성
이 주석이 있어야만 이해할 수 있는 코드라면 이미 잘못된 것이 아닐지?

2022-09-28 09:16 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/order/domain/ProductOrder.java
> +        productOrder.setCount(count);
여기도 setter 말고..!

2022-09-28 09:16 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/order/domain/ProductOrder.java
> +    }
도메인 안에 직접 로직을 가지는거 아주 좋아요👍

2022-09-28 09:16 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/order/ui/OrderController.java
>  @RequestMapping("/order")
```suggestion
@RequestMapping("/orders")
```

REST 표현은 복수가 더 낫겠네요!

2022-09-28 09:16 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/order/ui/OrderController.java
> +    }
오.. 이 API 의 의도를 좀 더 설명해줬으면...!

2022-09-28 09:16 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/order/ui/OrderController.java
> +    // 주문 상품과 수량을 선택 후 버튼을 누르면 실행
버튼을 누르는건 클라이언트의 행위인데 서버에서 알 필요가 있을까요? 우리는 요청만 있으면 되는데...

2022-09-28 09:16 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/order/ui/OrderController.java
> +    }
DTO 를 만들어서 body 로 받는게 더 낫지 않을까요?

2022-09-28 09:16 UTC, soulgchoi commented on backend/main-service/src/test/java/kkakka/mainservice/order/application/OrderServiceTest.java
> +@Transactional
테스트에서 `@Transactional` 은 동작이 좀 달라서, 좀 더 알아보고 적용하기를 추천합니다!

2022-09-28 09:16 UTC, soulgchoi commented on backend/main-service/src/test/java/kkakka/mainservice/order/application/OrderServiceTest.java
> +    public void productOrderOneTest_success() {
👍

2022-09-28 09:16 UTC, soulgchoi commented on backend/main-service/src/test/java/kkakka/mainservice/order/application/OrderServiceTest.java
> +        int orderCount = 2; //주문수량
orderCount 는 주문수량이다...

2022-09-28 09:16 UTC, soulgchoi commented on backend/main-service/src/test/java/kkakka/mainservice/order/application/OrderServiceTest.java
> +        Product product = productRepository.findById(1L).get();
기본 데이터로 회원과 상품을 저장하는건 비즈니스 로직인데, 테스트에서 동일한 데이터로 테스트 하는게 맞는걸까요?
그리고 `ProductController`의 `init()` 메서드를 없애버리면 이 테스트는 더이상 제대로 동작하지 않겠죠.
테스트 환경에 대해 좀 더 생각해보면 좋겠습니다!

2022-09-28 09:16 UTC, soulgchoi commented on backend/main-service/src/test/java/kkakka/mainservice/order/application/OrderServiceTest.java
> +
```suggestion
```
이런 개행 하나도 컨벤션을 위해 신경쓰면 좋겠어용!

2022-09-29 03:07 UTC, soulgchoi reviewed
어제 못본 부분들 추가로 코멘트 남겼습니다!ㅎㅎ
특히 재고처리 같은 부분은 우리 서비스에서 충분히 컨트롤할 수 있는 부분이므로 unchecked exception 으로 throw 해서 처리하는게 더 좋을거라고 생각되네요!

2022-09-29 03:07 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/order/ui/dto/ProductOrderRequest.java
> +    }
테스트용 생성자가 필요하다면 테스트를 고칠 수는 없을까요?ㅎㅎ

2022-09-29 03:07 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/product/domain/Product.java
> +    //TODO: 2022.09.28 프론트단에서 수량이상 선택못하게 막으면 필요없는 로직이지 않을까? -hyeyeon
프론트 - 백은 항상 별개로 생각하고 할 수 있는 예외처리는 했으면 좋겠어요ㅎㅎ

2022-09-29 03:07 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/product/domain/Product.java
> +            throw new Exception("수량이 부족합니다.");
일부러 `Exception`을 사용해서 chekced exeption 을 의도한건가요? 
하지만 컨트롤러까지 올라가도 처리하는 부분이 없어서 예외처리가 제대로 안될거 같습니다~

로직 순서도 생각해봐야 할 것 같아요. 일단 감소시키고 0보다 적으면 예외를 발생시켜서 롤백하는 게 의도한 방법인가요?
먼저 충분한 재고가 있는지 확인하고 예외처리 하는게 더 자연스럽지 않을까 생각이 듭니다~
그렇다면 서비스 레이어에서 `product` 도메인으로 구매 가능한지 메시지를 던져 응답을 받은 뒤에 나머지 로직을 진행하면 좋을 것 같아요~

2022-09-29 03:07 UTC, soulgchoi commented on backend/main-service/src/test/java/kkakka/mainservice/order/application/OrderServiceTest.java
> +    }
이렇게 만들면 모든 테스트 메서드마다 계속 회원을 생성해서 `member`에 할당할 것 같은데요, 
상품 주문에서 다른 회원이 필요한 경우는 없으므로 상수로 회원을 등록한 뒤에 테스트를 수행하는 것도 방법일 것 같습니다~

2022-09-29 03:07 UTC, soulgchoi commented on backend/main-service/src/test/java/kkakka/mainservice/order/application/OrderServiceTest.java
> +    public void productOrderMoreTest_success() throws Exception {
1L, 2L은 프로덕션 코드에서 저장한 값인거 같네요.
실제 사용자 환경과 테스트 환경에서 동일한 데이터를 써도 괜찮을까요?
테스트에서 삭제할 수도 있고, 사용자가 잘못된 테스트 데이터를 조회할 수도 있을 것 같네요...

그리고 저는 이 테스트를 봐서는 왜 가격이 2000*2 + 1000*3이 나와야 하는지 모르겠어요.
구매하는 요청을 만들 때 사용한 `Product` 객체에서 `product.getPrice()` 이런 식으로 불러와야 구매한 상품의 가격을 제대로 계산했구나 알 수 있지 않을까요?

2022-09-29 03:07 UTC, devpoooh commented on backend/main-service/src/main/java/kkakka/mainservice/order/application/OrderService.java
> +@Transactional
트랜잭션은 좀 더 공부해본 다음에 적용해보도록 하겠습니다~

2022-09-29 03:11 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/order/application/OrderService.java
> +@Transactional
일단 클래스 레벨에서는 `@Transactional(readOnly = true)` 로 설정하고 변경 연산(삽입, 수정, 삭제)이 일어나는 메서드들은 메서드 레벨에서 `@Transactional` 어노테이션 다시 붙여주세요~

2022-09-29 03:12 UTC, devpoooh commented on backend/main-service/src/main/java/kkakka/mainservice/order/domain/Order.java
> +    public static Order createOrder(Member member, int totalPrice, List<ProductOrder> productOrders) {
네 반영하겠습니다~

2022-09-29 05:31 UTC, devpoooh commented on backend/main-service/src/main/java/kkakka/mainservice/order/domain/Order.java
> +        return order;
네! setter의 경우 객체의 일관성 때문이라고 알고 있는데 생성자를 사용하면 매개변수에 따른 대응이나 가독성에 문제도 있다고 하네요. 그 방안으로 빌더 패턴을 사용한다고 하는데 저희 상황에서도 좋은 방안인건지? 또 그만큼 많이 사용하는 편인지도 궁금해지네요.
~~(@builder를 사용하지않으면 클래스가 좀 지저분해 보이기도 하고,,,)~~
잘 몰라서 의견이 듣고싶습니다!

2022-09-29 05:47 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/order/domain/Order.java
> +        return order;
일단 `@Builder` 는 롬복이 제공해주는 기능이라 다른 대안을 찾거나 직접 빌더를 구현하거나 하는 방법들이 있겠져.
(롬복은 코드가 라이브러리 의존적이 되고 사이드 이펙트가 발생할 수 있기 때문에 호불호가 있는 기술입니다.)
부생성자를 만들거나 `정적 팩토리 패턴`을 활용해서 생성할 수도 있습니다. 물론 이 방법들도 매개변수 타입이나 이런거 때문에 말한것처럼 대응에 문제가 생길 수도 있어서 그때는 빌더 패턴이 더 효율적일거 같네요~
https://kwonnam.pe.kr/wiki/java/lombok/pitfall
여기도 참고하면 좋을거 같아요!

2022-09-29 05:59 UTC, devpoooh commented on backend/main-service/src/main/java/kkakka/mainservice/order/domain/Order.java
> +        return order;
오오... 정적 팩토리 패턴... 
정말 많이 배워갑니다.☺ 참고 자료까지 감사합니다!

2022-09-29 06:00 UTC, devpoooh commented on backend/main-service/src/main/java/kkakka/mainservice/order/domain/Order.java
> +    }
오오... 스트림 공부가 필요해보이네요. 이부분은 좀 더 이해한 후에 적용해보겠습니다!

2022-09-29 06:02 UTC, devpoooh commented on backend/main-service/src/main/java/kkakka/mainservice/order/domain/ProductOrder.java
> +    //주문 상품, 가격, 수량 정보를 사용해서 주문상품 엔티티 생성
네에... 바로 지워버려!

2022-09-29 06:12 UTC, devpoooh commented on backend/main-service/src/main/java/kkakka/mainservice/order/ui/OrderController.java
>  @RequestMapping("/order")
네 수정하겠습니다~

2022-09-29 06:22 UTC, devpoooh commented on backend/main-service/src/main/java/kkakka/mainservice/order/ui/OrderController.java
> +    }
메인화면에서 상품 주문을 선택했을 때 GET방식으로 어떤 정보들을 가지고 와야하는지 까먹을까봐 적어뒀었습니다.

2022-09-29 06:22 UTC, devpoooh commented on backend/main-service/src/main/java/kkakka/mainservice/order/ui/OrderController.java
> +    // 주문 상품과 수량을 선택 후 버튼을 누르면 실행
네에...

2022-09-29 06:23 UTC, devpoooh commented on backend/main-service/src/main/java/kkakka/mainservice/order/ui/OrderController.java
> +    }
네 수정하겠습니다!!

2022-09-29 06:23 UTC, devpoooh commented on backend/main-service/src/test/java/kkakka/mainservice/order/application/OrderServiceTest.java
> +        int orderCount = 2; //주문수량
그렇다...

2022-09-29 06:36 UTC, devpoooh commented on backend/main-service/src/main/java/kkakka/mainservice/product/domain/Product.java
> +            throw new Exception("수량이 부족합니다.");
그러네요! 먼저 재고를 확인하고 처리하는게 좀 더 자연스럽고 간단해지는 로직같습니다.

제가 의도했던 바는 말씀해주신 것처럼 일단 감소를 시키고 0보다 적게되면 롤백하는 의도였습니다.

`product` 도메인에서도 구매 수량이 필요하지만 만약 주문창에서 수량 변경을 하게 된다면 여기서도 필요하지 않을까라는 생각이 듭니다.

2022-09-30 02:42 UTC, omj9803 approved these changes
많이 배워갑니당~👍🏻

2022-09-30 02:42 UTC, omj9803 commented on backend/main-service/src/main/java/kkakka/mainservice/order/application/OrderService.java
> +@Transactional
@transactional 은 변경이 필요한 메소드에 붙이는게 좋을 거 같습니다!
클래스 단위에서는 readonly 옵션은 어떠한지,,

2022-10-11 00:58 UTC, soulgchoi approved these changes

2022-10-11 03:16 UTC, merged