feat: 최신순으로 주문내역 조회
LOTTE-5IVE/kka-kka pull request #45
Opened 2022-09-30 07:47 UTC by devpoooh

## Resolve #26 
### 설명
- 내가 주문한 주문내역 정보 API 구현
   - 최신순으로 정렬
- 주문 <-> 상품주문 양방향으로 변경

2022-10-04 03:34 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/order/ui/OrderController.java
> +    public ResponseEntity<Void> order(@RequestBody OrderRequest orderRequest) throws Exception {
```suggestion
    public ResponseEntity<Void> order(@RequestBody OrderRequest orderRequest) {
```

내부에 딱히 checked exception 없는거 같은데 확인해주세요!

2022-10-04 03:35 UTC, soulgchoi requested changes
테스트 깨지는거 같은데 확인 부탁드립니다!

2022-10-04 03:35 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/order/ui/OrderController.java
> +    public ResponseEntity<Void> order(@RequestBody OrderRequest orderRequest) throws Exception {
```suggestion
    public ResponseEntity<Void> order(@RequestBody OrderRequest orderRequest) {
```
checked exception 발생하는 부분 없는거 같은데 확인해주세요!

2022-10-05 01:01 UTC, devpoooh commented on backend/main-service/src/main/java/kkakka/mainservice/order/ui/OrderController.java
> +    public ResponseEntity<Void> order(@RequestBody OrderRequest orderRequest) throws Exception {
네 확인했습니다!

2022-10-05 05:25 UTC, soulgchoi approved these changes

2022-10-07 00:22 UTC, soulgchoi approved these changes

2022-10-07 00:23 UTC, devpoooh commented
@omj9803 @tlsdnwn55 확인 부탁드려요~

2022-10-07 00:24 UTC, omj9803 approved these changes
고생하셨슴다!!!!! 👍🏻

2022-10-07 00:24 UTC, omj9803 commented on backend/main-service/src/main/java/kkakka/mainservice/order/ui/dto/OrderRequest.java
> +public class OrderRequest {
왜 `OrderRequestDto` 에서 `OrderRequest` 로 바꾼건가요?.. 그냥 궁금해서..

2022-10-07 00:27 UTC, merged