refactor: 장바구니 멤버 검증 로직 추가 및 리팩토링
LOTTE-5IVE/kka-kka pull request #46
Opened 2022-10-04 08:05 UTC by tlsdnwn55

## Resolve #16 #21 

### 설명
- dev 브랜치에 Oauth 인증 로직이 추가됨에 따라 장바구니 컨트롤러에서 멤버 검증 로직을 추가하였습니다.
- 멤버 검증 로직을 추가하면서 삭제 메소드의 문제점을 발견함에 따라 쿼리를 수정하였습니다.

2022-10-05 04:55 UTC, soulgchoi commented
related #59

2022-10-05 05:38 UTC, soulgchoi requested changes
테스트 다 실패하는데 확인해주세요!ㅎㅎ

2022-10-05 05:38 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +@AllArgsConstructor
롬복을 쓴다면 `@RequiredArgsConstructor`가 더 나을거 같아요!

2022-10-05 05:38 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
>              // TODO: 장바구니 없을 때 처리
처리 된거 아닌가여??

2022-10-05 05:38 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +
```suggestion
```

2022-10-05 05:38 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +                cartItemRepository.deleteCartItemById(deleteRequestId,loginMemberId));
띄어쓰기가 묘한걸 보니 포맷 적용 안된거 같은 느낌이 드네요...!
우리 노션에 코드 컨벤션 부분도 확인해주세요!

2022-10-05 05:38 UTC, soulgchoi commented on backend/main-service/src/test/java/kkakka/mainservice/cart/ui/CartAcceptanceTest.java
```suggestion
```

2022-10-05 05:38 UTC, soulgchoi commented on backend/main-service/src/test/java/kkakka/mainservice/cart/ui/CartAcceptanceTest.java
> +        CartResponseDto result = cartService.findAllCartItemByMemberId(member.getId());
`result` 를 쓰는 곳은 없네요?!

2022-10-06 07:15 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +@AllArgsConstructor
수정완료

2022-10-06 07:15 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
>              // TODO: 장바구니 없을 때 처리
수정완료

2022-10-06 07:16 UTC, tlsdnwn55 commented on backend/main-service/src/main/java/kkakka/mainservice/cart/application/CartService.java
> +                cartItemRepository.deleteCartItemById(deleteRequestId,loginMemberId));
귀신같으시네요 !

2022-10-06 08:38 UTC, soulgchoi approved these changes

2022-10-06 08:39 UTC, merged