feat: 쿠폰 CRUD 기능 구현
LOTTE-5IVE/kka-kka pull request #67
Opened 2022-10-06 01:11 UTC by omj9803

## Resolve #27 #28 #65 #66 

### 설명
- 관리자
  - 쿠폰 등록 : 등급 쿠폰/일반 쿠폰 나누어 등록할 수 있습니다.
  - 쿠폰 사용 (삭제) : 사용여부 `isUsed` 를 0 -> 1 로 바꾸어 사용 중지합니다.
  - 모든 쿠폰 조회 (삭제 포함) : 생성된 모든 쿠폰을 조회할 수 있습니다. 삭제된 쿠폰도 조회합니다.
 
- 사용자
  - 쿠폰 다운로드 : 쿠폰을 다운로드 하여 `MemberCoupon` 에 저장합니다.
  - 쿠폰 사용 : 쿠폰 사용여부를 변경합니다.
  - 사용 가능한 쿠폰 조회 : `MemberCoupon` 에서 사용 가능한 쿠폰을 보여줍니다.
  - 다운 가능한 쿠폰 조회 : `Coupon` 에서 다운 가능한 쿠폰을 보여줍니다.

### 기타
- 상품이나 장바구니와 연관관계에 대해 추가 구현이 필요합니다.
- 테스트 케이스에 대한 추가 구현이 필요합니다.

2022-10-06 05:49 UTC, soulgchoi requested changes
`test/member/acceptance` 참고해서 인수테스트 작성해주세요~
그리고 쿠폰 테스트 외 다른 테스트가 실패하네요 확인해주세요!

2022-10-06 08:37 UTC, soulgchoi requested changes
어려운 기능인데 구현하느라 고생하셨습니다~
코멘트 몇개 남겼으니 확인해주시고, 다른 의견이 있다면 얼마든지 말해주세요!
다만 기능 테스트가 제대로 되지 않았으니 요청/응답은 꼭 테스트를 거쳐 주시길 바랍니다.

2022-10-06 08:37 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/ui/CouponController.java
> +    /* 쿠폰 등록 */
이런 주석은 없어도 될거같아요~

2022-10-06 08:37 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/ui/CouponController.java
> +    }
이건 아직 구현 안된 기능이죠? 구현 완료한 기능들이랑 같은 패턴으로 작성했길래 될줄 알았어요~

2022-10-06 08:37 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/ui/dto/CouponRequestDto.java
> +    private LocalDateTime registeredAt;
`registeredAt` 은 엔티티 생성할 때 자동으로 `LocalDateTime.now()`를 넣어주는데 요청으로 받을 필요가 있을까요?

2022-10-06 08:37 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/CouponService.java
> +    @NotNull
이 어노테이션은 단순히`null` 반환하면 안된다고 표시만 해주는건가요? 
딱히 처리하는 부분이 없는데 어떤 의미가 있는지...

2022-10-06 08:37 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/CouponService.java
> +        return category;
```suggestion
        return categoryRepository.findById(couponRequestDto.getCategoryId())
            .orElseThrow(IllegalArgumentException::new);
```
바로 리턴해도 될거같아요ㅎㅎㅎ

2022-10-06 08:37 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/CouponService.java
> +        }
비회원일 경우 서비스 레이어까지 들어올 필요가 있을까요?
그리고 주석 없이도 충분히 코드만으로 알 수 있는 정보라고 생각합니다!

2022-10-06 08:37 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/CouponService.java
> +        return false;
`Coupon` 내부에서 도메인 로직을 수행하도록 만드는게 더 좋을거 같아요!
`coupon.isExpired()` 이런 식으로 구현하면 더 객체지향적이지 않을까요? 
이렇게 되면 메서드를 분리하지 않아도 `downloadCoupon` 이라는 하나의 행위 안에서 표현될 수 있다고 생각합니다

2022-10-06 08:37 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/CouponService.java
> +    }
사용 안하는 메서드인데 역할이 뭘까요ㅎㅎ
개인적으로 어차피 구현할 기능이니까 만들어둔다는 거라면.. 오버엔지니어링의 가능성이 있어서 지양하는 편입니닷
다른 의견이 있다면 말해주세요!

2022-10-06 08:37 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/CouponService.java
> +    public List<Coupon> findUsableCoupons(Long memberId) {
이런 메서드명 좋아요👍
메서드명만 봐도 어떤 일을 하는 메서드인지 잘 읽히기 때문에 주석은 필요없다는 게 주석에 대한 제 생각입니다!
꼭 필요하다고 느낀다면 의견을 듣고 조율하고 싶어요

2022-10-06 08:37 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/CouponService.java
> +        return coupons;
왜 회원-쿠폰과 쿠폰을 따로 찾아오지? 라고 생각했는데 `MemberCoupon` 과의 연관관계가 없어서 그러네요.
복합키 테이블도 엔티티 연관관계를 통해 탐색할 수 있어야하지 않을까요? 그러면 조인해서 쿠폰을 바로 찾을 수 있을거고, 
(테스트를 해봐야 알겠지만) 성능상 다른 점들도 확인할 수 있겠지요

2022-10-06 08:37 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/CouponService.java
> +    }
다운로드 관련 기능이 테스트코드에만 있네요..?🤔

개인적으로는 if 문 안에 여러 조건을 나열하는 것보다 조건을 하나씩 early return 하는 것을 선호합니다!
해당 메서드는 다운로드 가능한지 검증하는 메서드를 분리해서 `stream` 의 `filter` 기능을 사용하면 어떤가 합니다.
주석이나 코드 만으로 메서드를 이해하기 어려웠어요😅

2022-10-06 08:37 UTC, soulgchoi commented on backend/main-service/src/test/java/kkakka/mainservice/coupon/CouponRepositoryTest.java
> +    private EntityManager entityManager;
이건 사용 안하네요!

2022-10-06 08:37 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/member/member/domain/Member.java
> +    }
테스트용 생성자 때문에 프로덕션 코드가 변경되는 것보다 테스트를 수정하는게 맞지 않을까요?
`Grade` 만 가지고 있는 `Member` 는 비즈니스 로직 상 잘못된 유형의 회원인데, 개발하다가 누가 모르고 사용해서 사이드 이펙트가 발생할 가능성이 생겨버리네요ㅎㅎ
그리고 생성자 만드는 방식도 문제가 있네요. 지금 `Member` 는 전체 매개변수가 필요한 생성자는 `private`으로 만들고 정적 팩터리 메서드로 필요한 인자만 받아서 생성하게 만들었거든요...

2022-10-06 08:37 UTC, soulgchoi commented on backend/main-service/src/test/java/kkakka/mainservice/coupon/CouponServiceTest.java
> +        Member member = new Member();
`fixture/TestMember` 참고해주세요ㅎㅎ 테스트에 활용할 수 있도록 테스트 데이터를 만들었습니다!

2022-10-06 08:37 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/CouponService.java
> +        if (PriceRule.GRADE_COUPON.equals(couponRequestDto.getPriceRule())) {
if 문으로 구분하기보다 전략 패턴이나 팩토리 패턴을 활용해서 `PriceRule` 에 따라 다른 쿠폰을 생성하도록 추상화 할 수 있지 않을까요?
지금도 코드가 충분히 긴데 만약 개발하다가 다른 종류의 쿠폰이 추가된다고 하면 더 유지보수하기 힘들어질 것 같아요

2022-10-06 10:30 UTC, soulgchoi commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/domain/MemberCoupon.java
> +    private MemberCouponId memberCouponId;
```suggestion
    private MemberCouponId memberCouponId;
    
    @MapsId(value = "memberId")
    @ManyToOne(fetch = FetchType.LAZY)
    private Member member;

    @MapsId(value = "couponId")
    @ManyToOne(fetch = FetchType.LAZY)
    private Coupon coupon;
```

이런 식으로 `MemberCoupon` 과 `Member`, `Coupon` 사이에 연관관계 매핑을 통해 `MemberCoupon` 조회할 때 fetch join 으로 정보를 한 번에 가져오면 좋을 것 같아요~!

2022-10-07 02:44 UTC, omj9803 commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/ui/CouponController.java
> +    }
넵 Controller 구현해서 다시 올리겠습니다!

2022-10-07 08:06 UTC, omj9803 commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/ui/dto/CouponRequestDto.java
> +    private LocalDateTime registeredAt;
맞습니다 ㅜ 수정하겠습니다ㅜ

2022-10-07 08:31 UTC, omj9803 commented on backend/main-service/src/main/java/kkakka/mainservice/coupon/application/CouponService.java
> +    }
넵 수정하겠습니당 😅

2022-10-07 08:32 UTC, omj9803 commented on backend/main-service/src/test/java/kkakka/mainservice/coupon/CouponRepositoryTest.java
> +    private EntityManager entityManager;
테스트는 다시 수정 보완해서 올리겠읍니당 !

2022-10-13 03:41 UTC, omj9803 commented
@soulgchoi @tlsdnwn55 @devpoooh 확인 부탁드립니😁🔫

2022-10-13 05:32 UTC, tlsdnwn55 approved these changes
쿠폰 진짜 어려워 보인다 고생이 많구나 ! 점점 장인이 되어가는듯

2022-10-18 05:51 UTC, soulgchoi approved these changes
고생하셨습니다!

2022-10-18 06:10 UTC, omj9803 commented
feat: 쿠폰, 할인 기능 구현

2022-10-18 06:11 UTC, merged